version: '3.1'

services:
  db:
    container_name: movie_mysql
    image: mysql:8.0.39
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: movie_secret
      MYSQL_DATABASE: movie